name: Running Code Coverage

# on: [push, pull_request]
on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [14.x, 16.x, 18.x, 19.x, 20.x]
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        # with:
          # -depth: 2
          # persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: project
        run: yarn --immutable

      - name: Run tests
        working-directory: project
        run: yarn run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          